---
platform: linux
inputs:
- name: git-repo
outputs:
- name: distribution-repository
- name: stage-git-repo
params:
  RELEASE_TYPE:
  CI: true
  GRADLE_ENTERPRISE_CACHE_USERNAME:
  GRADLE_ENTERPRISE_CACHE_PASSWORD:
caches:
- path: maven
- path: gradle
run:
  path: git-repo/ci/scripts/stage.sh
