github-repo: "https://github.com/spring-io/spring-asciidoctor-backends.git"
github-repo-name: "spring-io/spring-asciidoctor-backends"
github-project-name: "spring-asciidoctor-backends"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "main"
build-name: "spring-asciidoctor-backends"
ci-image-name: "spring-asciidoctor-backends-ci"
task-timeout: 1h00m
